name: Publish Package

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: revolist/revogrid-actions
          ref: main
          path: ./actions
          token: ${{ secrets.REPO_TOKEN }}
      - uses: ./actions/release-pkg
        with:
          token: ${{ secrets.GITHUB_TOKEN }}